/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  ContactAttempts: () => import('#controllers/contact_attempts_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Employees: () => import('#controllers/employees_controller'),
  Imports: () => import('#controllers/imports_controller'),
  Media: () => import('#controllers/media_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Operations: () => import('#controllers/operations_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
  Vehicles: () => import('#controllers/vehicles_controller'),
  Visitors: () => import('#controllers/visitors_controller'),
}
