/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApprovalRequestSchema extends BaseModel {
  static $columns = ['alternatePhone', 'birthDate', 'companyName', 'cpf', 'createdAt', 'email', 'employeeId', 'fullName', 'id', 'normalizedCpf', 'phone', 'photoPath', 'rejectionReason', 'roleName', 'status', 'updatedAt', 'vehicleColor', 'vehicleManufacturer', 'vehicleModel', 'vehiclePlate', 'vehicleType', 'vehicleYear'] as const
  $columns = ApprovalRequestSchema.$columns
  @column()
  declare alternatePhone: string | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare companyName: string | null
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare employeeId: number | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare normalizedCpf: string
  @column()
  declare phone: string | null
  @column()
  declare photoPath: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare roleName: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleColor: string | null
  @column()
  declare vehicleManufacturer: string | null
  @column()
  declare vehicleModel: string | null
  @column()
  declare vehiclePlate: string | null
  @column()
  declare vehicleType: string | null
  @column()
  declare vehicleYear: number | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'normalizedName', 'status', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare normalizedName: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactAttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'employeeId', 'id', 'message', 'status', 'targetPhone', 'updatedAt', 'userId', 'visitorId', 'whatsappUrl'] as const
  $columns = ContactAttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare status: string
  @column()
  declare targetPhone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare visitorId: number | null
  @column()
  declare whatsappUrl: string
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['alternatePhone', 'birthDate', 'companyId', 'companyName', 'costCenterCode', 'costCenterDescription', 'cpf', 'createdAt', 'email', 'fullName', 'id', 'normalizedCpf', 'normalizedName', 'notes', 'phone', 'photoPath', 'roleName', 'seniorImportId', 'seniorRaw', 'seniorSourceKey', 'status', 'updatedAt'] as const
  $columns = EmployeeSchema.$columns
  @column()
  declare alternatePhone: string | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare companyId: number | null
  @column()
  declare companyName: string | null
  @column()
  declare costCenterCode: string | null
  @column()
  declare costCenterDescription: string | null
  @column()
  declare cpf: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare normalizedCpf: string | null
  @column()
  declare normalizedName: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare photoPath: string | null
  @column()
  declare roleName: string | null
  @column()
  declare seniorImportId: number | null
  @column()
  declare seniorRaw: string | null
  @column()
  declare seniorSourceKey: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SeniorImportSchema extends BaseModel {
  static $columns = ['createdAt', 'detectedHeaderRow', 'errorCount', 'errorsJson', 'finishedAt', 'id', 'importedCount', 'skippedCount', 'sourceFileName', 'sourcePath', 'sourceType', 'startedAt', 'status', 'totalRows', 'updatedAt', 'updatedCount'] as const
  $columns = SeniorImportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detectedHeaderRow: number | null
  @column()
  declare errorCount: number
  @column()
  declare errorsJson: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare importedCount: number
  @column()
  declare skippedCount: number
  @column()
  declare sourceFileName: string | null
  @column()
  declare sourcePath: string | null
  @column()
  declare sourceType: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare totalRows: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedCount: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'employeeId', 'id', 'licensePlate', 'manufacturer', 'model', 'normalizedPlate', 'notes', 'photoPath', 'status', 'updatedAt', 'vehicleType', 'year'] as const
  $columns = VehicleSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licensePlate: string
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare normalizedPlate: string
  @column()
  declare notes: string | null
  @column()
  declare photoPath: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleType: string
  @column()
  declare year: number | null
}

export class VisitorSchema extends BaseModel {
  static $columns = ['companyName', 'cpf', 'createdAt', 'enteredAt', 'exitedAt', 'fullName', 'id', 'licensePlate', 'manufacturer', 'model', 'normalizedCpf', 'normalizedName', 'normalizedPlate', 'notes', 'updatedAt', 'vehicleType', 'visitReason', 'year'] as const
  $columns = VisitorSchema.$columns
  @column()
  declare companyName: string | null
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare enteredAt: DateTime
  @column.dateTime()
  declare exitedAt: DateTime | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licensePlate: string
  @column()
  declare manufacturer: string | null
  @column()
  declare model: string | null
  @column()
  declare normalizedCpf: string
  @column()
  declare normalizedName: string
  @column()
  declare normalizedPlate: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleType: string | null
  @column()
  declare visitReason: string | null
  @column()
  declare year: number | null
}
