import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('companies', (table) => {
      table.increments('id').notNullable()
      table.string('name', 160).notNullable().unique()
      table.string('normalized_name', 180).notNullable().index()
      table.string('status', 20).notNullable().defaultTo('active')
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('employees', (table) => {
      table.increments('id').notNullable()
      table.string('full_name', 180).notNullable()
      table.string('normalized_name', 200).notNullable().index()
      table.date('birth_date').nullable()
      table.string('cost_center_code', 40).nullable().index()
      table.string('cost_center_description', 220).nullable().index()
      table.string('role_name', 140).nullable().index()
      table
        .integer('company_id')
        .unsigned()
        .references('id')
        .inTable('companies')
        .onDelete('SET NULL')
      table.string('company_name', 160).nullable().index()
      table.string('phone', 32).nullable().index()
      table.string('alternate_phone', 32).nullable()
      table.string('email', 254).nullable().index()
      table.string('photo_path', 500).nullable()
      table.string('senior_source_key', 220).nullable().unique()
      table.text('senior_raw').nullable()
      table.string('status', 20).notNullable().defaultTo('active').index()
      table.text('notes').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('vehicles', (table) => {
      table.increments('id').notNullable()
      table
        .integer('employee_id')
        .unsigned()
        .references('id')
        .inTable('employees')
        .onDelete('CASCADE')
      table.string('license_plate', 12).notNullable()
      table.string('normalized_plate', 12).notNullable().unique()
      table.string('vehicle_type', 40).notNullable().defaultTo('car')
      table.string('manufacturer', 80).nullable().index()
      table.string('model', 100).nullable().index()
      table.integer('year').nullable().index()
      table.string('color', 40).nullable()
      table.string('photo_path', 500).nullable()
      table.string('status', 20).notNullable().defaultTo('active').index()
      table.text('notes').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('visitors', (table) => {
      table.increments('id').notNullable()
      table.string('full_name', 180).notNullable()
      table.string('normalized_name', 200).notNullable().index()
      table.string('cpf', 20).notNullable()
      table.string('normalized_cpf', 11).notNullable().index()
      table.string('license_plate', 12).notNullable()
      table.string('normalized_plate', 12).notNullable().index()
      table.string('vehicle_type', 40).nullable()
      table.string('manufacturer', 80).nullable()
      table.string('model', 100).nullable()
      table.integer('year').nullable()
      table.string('company_name', 160).nullable()
      table.string('visit_reason', 220).nullable()
      table.timestamp('entered_at').notNullable()
      table.timestamp('exited_at').nullable()
      table.text('notes').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('senior_imports', (table) => {
      table.increments('id').notNullable()
      table.string('source_type', 20).notNullable()
      table.string('source_file_name', 260).nullable()
      table.string('source_path', 600).nullable()
      table.string('status', 20).notNullable().defaultTo('pending').index()
      table.integer('detected_header_row').nullable()
      table.integer('total_rows').notNullable().defaultTo(0)
      table.integer('imported_count').notNullable().defaultTo(0)
      table.integer('updated_count').notNullable().defaultTo(0)
      table.integer('skipped_count').notNullable().defaultTo(0)
      table.integer('error_count').notNullable().defaultTo(0)
      table.text('errors_json').nullable()
      table.timestamp('started_at').nullable()
      table.timestamp('finished_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('contact_attempts', (table) => {
      table.increments('id').notNullable()
      table
        .integer('employee_id')
        .unsigned()
        .references('id')
        .inTable('employees')
        .onDelete('SET NULL')
      table
        .integer('visitor_id')
        .unsigned()
        .references('id')
        .inTable('visitors')
        .onDelete('SET NULL')
      table.integer('user_id').unsigned().references('id').inTable('users').onDelete('SET NULL')
      table.string('target_phone', 32).notNullable()
      table.text('message').notNullable()
      table.string('whatsapp_url', 1200).notNullable()
      table.string('status', 20).notNullable().defaultTo('opened').index()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })
  }

  async down() {
    this.schema.dropTable('contact_attempts')
    this.schema.dropTable('senior_imports')
    this.schema.dropTable('visitors')
    this.schema.dropTable('vehicles')
    this.schema.dropTable('employees')
    this.schema.dropTable('companies')
  }
}
