function traceVercelDependencies() {
  return [
    import('@adonisjs/auth'),
    import('@adonisjs/auth/auth_provider'),
    import('@adonisjs/auth/initialize_auth_middleware'),
    import('@adonisjs/auth/mixins/lucid'),
    import('@adonisjs/auth/session'),
    import('@adonisjs/core'),
    import('@adonisjs/core/app'),
    import('@adonisjs/core/bodyparser'),
    import('@adonisjs/core/bodyparser_middleware'),
    import('@adonisjs/core/encryption'),
    import('@adonisjs/core/env'),
    import('@adonisjs/core/hash'),
    import('@adonisjs/core/helpers'),
    import('@adonisjs/core/http'),
    import('@adonisjs/core/logger'),
    import('@adonisjs/core/providers/app_provider'),
    import('@adonisjs/core/providers/edge_provider'),
    import('@adonisjs/core/providers/hash_provider'),
    import('@adonisjs/core/providers/vinejs_provider'),
    import('@adonisjs/core/services/app'),
    import('@adonisjs/core/services/hash'),
    import('@adonisjs/core/services/router'),
    import('@adonisjs/core/services/server'),
    import('@adonisjs/core/transformers'),
    import('@adonisjs/cors'),
    import('@adonisjs/cors/cors_middleware'),
    import('@adonisjs/cors/cors_provider'),
    import('@adonisjs/inertia'),
    import('@adonisjs/inertia/inertia_middleware'),
    import('@adonisjs/inertia/inertia_provider'),
    import('@adonisjs/lucid'),
    import('@adonisjs/lucid/database_provider'),
    import('@adonisjs/session'),
    import('@adonisjs/session/session_middleware'),
    import('@adonisjs/session/session_provider'),
    import('@adonisjs/shield'),
    import('@adonisjs/shield/shield_middleware'),
    import('@adonisjs/shield/shield_provider'),
    import('@adonisjs/static'),
    import('@adonisjs/static/static_middleware'),
    import('@adonisjs/static/static_provider'),
    import('@adonisjs/vite'),
    import('@adonisjs/vite/vite_middleware'),
    import('@adonisjs/vite/vite_provider'),
    import('@libsql/client'),
    import('@libsql/sqlite3'),
    import('@tuyau/core/hooks'),
    import('@vinejs/vine'),
    import('csv-parse/sync'),
    import('edge.js'),
    import('knex'),
    import('knex-dynamic-connection'),
    import('knex-dynamic-connection/node_modules/knex/lib/util/helpers.js'),
    import('luxon'),
    import('read-excel-file/node'),
    import('reflect-metadata'),
    import('zod'),
  ]
}

void traceVercelDependencies

export { default } from '../build/bin/vercel.js'
